FROM node:18-alpine

WORKDIR /app
EXPOSE 3000 9229
RUN apk update && apk add tzdata npm
COPY ./ArchieMate.Frontend/package.json ./ArchieMate.Frontend/package-lock.json /app/
RUN npm install --include=dev

CMD ["npm", "run", "start:debug"]
